---
name: Code review using stylelint
author: Money Forward, Inc.
description: Analyze code statically using stylelint in Github actions
inputs:
  files:
    description: |
      Specify patterns by glob
      
      (Multiple patterns can be specified by separating them with line feed)
    required: false
  options:
    description: |
      Changes `stylelint` command line options.

      Specify the options in JSON array format.
      e.g.: '["-s", "css"]'
    required: false
  working_directory:
    description: Changes the current working directory of the Node.js process
    required: false
  reporter_type_notation:
    description: |
      Change the reporter.

      (Multiple can be specified separated by commas)
    required: false
runs:
  using: 'node12'
  main: 'dist/action/index.js'
branding:
  icon: 'search'
  color: 'orange'
